version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/venv # prevent venv from being overwritten

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules # prevent node_modules from being overwritten
